### PR TITLE
[IT Translation] Translate "/email show" command

### PR DESCRIPTION
**Pull request by Maxetto**
Updating again IT Translation.

### CODE REVIEW

**Comment by Maxetto** [comment]
Also, even with the latest Dev build, "/authme help" prints unlocalized short descriptions:
```
[18:15:56 INFO]: ==========[ Assistenza AuthMeReloaded ]==========
[18:15:56 INFO]: Comando: /authme
[18:15:56 INFO]: Descrizione breve: Main command
[18:15:56 INFO]: Comandi:
[18:15:56 INFO]:  /authme register: Register a player
[18:15:56 INFO]:  /authme unregister: Unregister a player
[18:15:56 INFO]:  /authme forcelogin: Enforce login player
[18:15:56 INFO]:  /authme password: Change a player's password
[18:15:56 INFO]:  /authme lastlogin: Player's last login
[18:15:56 INFO]:  /authme accounts: Display player accounts
[18:15:56 INFO]:  /authme email: Display player's email
[18:15:56 INFO]:  /authme setemail: Change player's email
[18:15:56 INFO]:  /authme getip: Get player's IP
[18:15:56 INFO]:  /authme spawn: Teleport to spawn
[18:15:56 INFO]:  /authme setspawn: Change the spawn
[18:15:56 INFO]:  /authme firstspawn: Teleport to first spawn
[18:15:56 INFO]:  /authme setfirstspawn: Change the first spawn
[18:15:56 INFO]:  /authme purge: Purge old data
[18:15:56 INFO]:  /authme resetpos: Purge player's last position
[18:15:56 INFO]:  /authme purgebannedplayers: Purge banned players data
[18:15:56 INFO]:  /authme switchantibot: Switch AntiBot mode
[18:15:56 INFO]:  /authme reload: Reload plugin
[18:15:56 INFO]:  /authme version: Version info
[18:15:56 INFO]:  /authme converter: Converter command
[18:15:56 INFO]:  /authme messages: Add missing messages
[18:15:56 INFO]:  /authme help: View help
```

**Comment by ljacqu** [comment]
Took me a while to understand your edit but I get what you mean, I'm working on fixing it :) Thanks

**Comment by Maxetto** [comment]
Also, as I thought, if you set your password as "help", you cannot register or login (Major issue if you change the password after registering).

Solutions: Block "help" as password or check if it's the right password before printing the actual help.

**Comment by sgdc3** [comment]
@Maxetto Thank you, could you open a new issue for the other issues please? ;)

**Comment by ljacqu** [comment]
+1 for new issue
just one thing: probably the simplest solution is to add "help" as a disallowed password in the config. This way we don't have this "weird" check in the code.

**Pull request merged**
