### PR TITLE
bStats

### PR DESCRIPTION
**Pull request by sgdc3**

### CODE REVIEW

**Comment by sgdc3** [comment]
It's still a beta, we need to wait for an official maven repository

**Comment by games647** [comment]
Yeah, currently it's just a gist not even a github repo where others could contribute.

**Comment by sgdc3** [comment]
>not even a github repo where others could contribute

https://github.com/BtoBastian/bStats

**Comment by games647** [comment]
I meant the metrics class

**Comment by sgdc3** [comment]
it is on gist

**Comment by sgdc3** [comment]
https://gist.github.com/BtoBastian/01cdf38e8d73024426c3b02d990f048d#file-metrics-java

**Comment by ljacqu** [comment]
> Yeah, currently it's just a gist

I think he knows, https://github.com/AuthMe/AuthMeReloaded/pull/215#issuecomment-275921025

**Comment by sgdc3** [comment]
Whoops, misread the comment, sorry.

**Pull request merged**
