### PR TITLE
Registration date and IP // null columns in DB

### PR DESCRIPTION
**Pull request by ljacqu**
Still a work in progress—PR for #792 and #814. I open up a PR this early for discussion and a preliminary review if someone has the time.

Work so far
- added columns for registration date and IP
- change MySQL to support not null for lastlogin and last_ip

Open points
- SQLite migration
- Need to handle purging logic... because after the change we will have accounts with `null` registration date, but also accounts with a `null` lastlogin date. Not sure what behavior is desired...
- I want to remove the default value for realname and email while we're doing changes to the DB (#814)

Any comments about the code so far or any ideas how the purging should be changed? Our current purging feature is basically to purge inactive accounts, which by two fields would basically be something like `purge if max(lastLoginDate, registrationDate) > NOW() - 40d` IMHO (if `40d` are configured)
Not to confuse with _Release accounts registered by mail and have not logged in_ #899.

Also what about max registration per IP? Do we go by registration IP or last IP?

### CODE REVIEW

**Comment by games647** [comment]
> purge if max(lastLoginDate, registrationDate) > NOW() - 40d

I think this is the best solution.

>Also what about max registration per IP? Do we go by registration IP or last IP??

I think it should be last IP and if last IP is null, because the player not logged in yet, we could take registration IP. This should consider:
* Player joined the first time and registered more accounts on the same day (registration IP == last IP)
* Existing player joined the server, but created another account later the day (last IP == current IP)
* Player registered on the forums without login, but then registered another account by directly joining the server without forum registration in case that's possible (registration IP == current IP)

**Comment by HexelDev** [comment]
> Also what about max registration per IP? Do we go by registration IP or last IP?

I'm going to define the two cases to analyze them better
###### 1st: registration IP

>  This case will use a static reference to the saved IPs list, **'x' accounts every IP**.

###### 2nd: last IP

> The dynamic nature of the IPs will interfere with this field, it will deny more then **'x' conteporary connections using the same IP**.

We could go with the first one to have some static point of interaction, the second one is not the scope of this function, am I right?

**Comment by HexelDev** [comment]
@games647 you just described the complex system I was thinking about... 
But I was not sure if it could really be worth it, a system based on dynamic data that could be analyzed only during specified time windows based on matching rules 

(I really like the idea but is it worth it? I can't find the answer XD)

**Comment by games647** [comment]
@HexelDev I rather thinks it's not worth it, because you can workaround it this limitation in many ways like disconnect your router or wait for the next day without logging in with your existing account.

**Comment by HexelDev** [comment]
Yeah that's my same point...

It's not possible to create a system that stem these cases... It should be too complex and still have weak points :/

**Comment by HexelDev** [comment]
> Need to handle purging logic... because after the change we will have accounts with null registration date, but also accounts with a null lastlogin date. Not sure what behavior is desired...
We could set all the `null` date value to the current date (`NOW()`), this will let the purge system works without issues.

**Comment by ljacqu** [comment]
That sounds great @HexelDev, without that default we'd have `reg_date` that can have NULL entries and also the `last_login` column, which would give us four cases to discuss:

```
name | reg_date | last_date
---- | -------- | ----------
 a   |  NULL    |  12
 b   |  13      |  NULL
 c   |  12      |  13
 d   |  NULL    |  NULL
```
- a) is what will be in the DB of anyone using AuthMe after this migration. Maybe also with some forum integration that is wrongly set up?
- b) is what might happen in the future with email registration: user registered but has never logged in.
- c) is what will be in the DB once a new user registers and logs in
- d) should never happen during gameplay, but converting data from another plugin might generate this.

I was going to argue against using a default value for registration date since with this PR we're actually trying to _remove_ default values—however, a default would prevent us from having case d), which would complicate things for us and for the user. In the end I'd agree with the `NOW()` default, because in regards to purging it's a good default that will never cause any record to be purged to soon.

**Comment by ljacqu** [comment]
In order to actually finish this PR sometime I will have to revert the removal of default values for email and IP. While testing forum integrations I realized that this breaks our integration into certain forums that have `NOT NULL` on their email column. 

I have ideas how to tackle it, but since it provides no value to the user (besides having a slimmer database) I'll focus on #792 for the time being, as other issues depend upon these columns being added.

**Comment by ljacqu** [comment]
Decision: commits so far get squashed and pusehd to a new branch, and the changes of the new branch will be:
- Add column for registration date and registration IP.
  - registration date is `NOT NULL` (as explained by @HexelDev in https://github.com/AuthMe/AuthMeReloaded/pull/1332#issuecomment-334418187)
    - reasoning: need this data for purging. Current date is a good default if we don't have the information.
    - the default is implemented ON APPLICATION LAYER -> no `DEFAULT` set over SQL
  - registration ip is nullable. If we don't have the info we don't have it. Period.
- Despite my previous comment, also change last IP and last date to be nullable
  - Signals that user has never logged on... Again, if we don't have the info, we don't have it and deal with it. The `DEFAULT` values in SQL must die.

**Pull request closed without merging**
