### PR TITLE
IPB4 Improves

### PR DESCRIPTION
**Pull request by Krokit**
Support added for default group and prefix for table.

### CODE REVIEW

**Comment by ljacqu** [comment]
Thank you for the PR! I have no means to test this on either forum; the changes look OK technically so I would vote to merge.

@Krokit, with this change is it possible to register in-game with AuthMe and to then log into the Xenforo forum? In https://github.com/Xephi/AuthMeReloaded/issues/957#issuecomment-255649331 we were told that it doesn't work (yet).

**Comment by Krokit** [comment]
@ljacqu  Yes with Xenforo is broken but i will fix it. I know what and where to put. Authme and IPB 4 works in both ways(Register/Change password in web and reverse).

**Comment by ljacqu** [comment]
@Krokit Thanks for the feedback. Would you like this PR to be merged now, or do you want to keep it open for the Xenforo stuff?

**Comment by Krokit** [comment]
@ljacqu Let's keep it open for now.

**Comment by ljacqu** [comment]
No need to rush! Thanks for your work :)

**Comment by Krokit** [comment]
@ljacqu So i make a lot stuff but when user try to register from website their is error with column(Mysqli statement execute error : Field 'members_seo_name' doesn't have a default value)
members_seo_name = mySQLColumnName also same issues with salt and hash. Where i can set column to be null?

**Comment by ljacqu** [comment]
@Krokit I don't know anything about IPB or Xenforo. What website do you mean?
 You can set a column to allow `NULL` in SQL, but if the forum software sets `members_seo_name` to be `NOT NULL` this might not be the proper approach.

**Comment by Krokit** [comment]
@ljacqu IPB 4 version is working without any errors. XenForo register check all columns in tables and if is empty give error. Yes i set to be NULL in phpmyadmin but if i make here in plugin to be null by default can cause a lot of bugs(password and salt main). So i think better way is to make tutorial how to fix xenforo table to works register without any errors. What  do you  think?

**Comment by Gnat008** [comment]
Changing the database tables of another program (especially a forum) does not exactly seem ideal to me...

**Comment by Krokit** [comment]
@Gnat008 Yes, i know but we change only columns made by Authme. So users doesn't need to change forum tables. :)

**Comment by Krokit** [comment]
I will try some tricks but maybe integration with xenforo will not be able due to XenForo register class.

**Comment by ljacqu** [comment]
> Yes, i know but we change only columns made by Authme.

So a column we (AuthMe) create needs to be changed? Which column is it and what is the change? I'm all up for creating a tutorial page, but of course if we can solve this problem otherwise that would be ideal =)

**Comment by Krokit** [comment]
@ljacqu mySQLColumnName, mySQLColumnPassword, mySQLColumnSalt, but if they can be null can cause a lot of bugs maybe.

**Comment by ljacqu** [comment]
@Krokit Those can't be nullable. But the mySQLColumnSalt can be disabled if it is configured to empty string, and shouldn't mySQLColumnName and mySQLColumnPassword be named after the Xenforo column name on the Xenforo table?

**Comment by Krokit** [comment]
@ljacqu Sorry I forget that salt can be disabled, mySQLColumnName store username in lowercase so in forum we need to use mySQLRealName for username. So for XenForo mySQLColumnPassword, mySQLColumnName need have option for disable. Ahh this XenForo is not easy like IPB.

**Comment by ljacqu** [comment]
Thanks for the explanations. How is the columnName (lowercase) handled in IPB? There I also assume IPB only uses a "mySqlColumnRealName", right? 
I don't have any ideas right now... I'll need to sleep on this.

> Ahh this XenForo is not easy like IPB.

:smile:

**Comment by Krokit** [comment]
@ljacqu In IPB mySQLColumnName  is used for seo link: 
example: https://example.com/profile/1.username

**Comment by ljacqu** [comment]
Thanks for the explanation. I'm still thinking about this! Right now I wonder if a trigger would be the best solution to have a non-null "mySQLColumnName" column.

**Comment by Krokit** [comment]
For now user register successfully in-game, but main problem is  forum.  Lets say we remove password column. Is this going to cause a bug in plugin when user register/login ? Because in config we set xenforo auth. Xenforo in Authme use other table .

**Comment by ljacqu** [comment]
You know what, if Xenforo is so different from the rest, how about we create a separate datasource for it? Assuming that the database schema is somewhat stable over the versions. I can help in creating a new the new data source as long as you know how to talk to the Xenforo tables :)

> For now you can added new things so users can use IPB 4.

So we merge this PR? :)

**Comment by ljacqu** [comment]
I have this "dangerous" idea of implementing a fully configurable data source where you can define what data lives in what table, and offering options like "add this value in this column on registration", and an option to base the lowercase name from a case-sensitive one...

But realistically (time / conplexity) for now we should look into creating a Xenforo datasource

**Comment by Krokit** [comment]
@Ijacqu  Yes merge this PR. Yes we can do this for xenforo but i doesn't know so much java, but i will try with your help  and if someone want to join.

**Comment by ljacqu** [comment]
You know Xenforo and I know Java... We can pull this off :) I'll contact you in a few days ;)

**Comment by Krokit** [comment]
Okay.

**Pull request merged**
