### PR TITLE
Use custom async thread execution pool

### PR DESCRIPTION
**Pull request by sgdc3**
@ljacqu @games647

### CODE REVIEW

**Comment by ljacqu** [comment]
I'm really confused, why is this PR a revert commit? Why was this on master and then reverted...?

As before, I think performance measurements proving that this approach is beneficial is necessary before we can merge to master.

**Comment by sgdc3** [comment]
@ljacqu Revert of a revert because my git client loves to mess with my local repo

**Comment by sgdc3** [comment]
@games647 any opinion on this?

**Comment by games647** [comment]
>As before, I think performance measurements proving that this approach is beneficial is necessary before we can merge to master.

Same opinion as @ljacqu 
>As before, I think performance measurements proving that this approach is beneficial is necessary before we can merge to master.

I guess it doesn't have any big benefits on performance side.

**Comment by sgdc3** [comment]
@games647 I disagree with you, atm a bot attack cause the crash of the server due to the huge amount of threads.

**Comment by Gnat008** [comment]
And does this actually help that? What exactly is the difference between this and the current method with regards to bots?

**Comment by sgdc3** [comment]
With a limited size thread pool the ammount of running threads is limited

**Comment by sgdc3** [comment]
With bukkit scheduler:
1 player join = 1 async thread is created
With limited thread pool:
1 player join = put in queue, create thread if current running threads < thread limit

**Comment by sgdc3** [comment]
@Gnat008 @games647 @ljacqu

**Comment by DNx5** [comment]
as https://github.com/AuthMe/AuthMeReloaded/pull/175 Antibot is no longer uses thread to detect bots.

**Comment by sgdc3** [comment]
.... I know, but we create new async threads everytime someone joins

**Comment by sgdc3** [comment]
On Player Join -> Async Task

**Comment by DNx5** [comment]
we kick the bot before they reach on player join listener, that shouldn't make a new join process.

**Pull request closed without merging**
