### PR TITLE
Update team.txt

### PR DESCRIPTION
**Pull request by MineSAT**
Update translators :P

### CODE REVIEW

**Comment by sgdc3** [comment]
@ljacqu I think we should remove the team file and move in into a wiki page, what do you think?

**Comment by MineSAT** [comment]
@sgdc3 I think it's great

**Comment by ljacqu** [comment]
@sgdc3 Agreed. Translators are already listed on https://github.com/AuthMe/AuthMeReloaded/wiki/Translators

**Comment by sgdc3** [comment]
https://github.com/AuthMe/AuthMeReloaded/wiki/Development-team

**Comment by ljacqu** [comment]
@sgdc3 Awesome! Thanks for creating the page

**Pull request closed without merging**
