### PR TITLE
#1109 - Simplify password recovery process

### PR DESCRIPTION
**Pull request by Gnat008**
A general summary of these changes can be found in @ljacqu's write-up in #1109.

### CODE REVIEW

**Comment by Gnat008** [comment]
As a note, I think Travis is currently borked; it builds fine locally.

**Comment by sgdc3** [comment]
[ERROR] /home/travis/build/AuthMe/AuthMeReloaded/src/main/java/fr/xephi/authme/command/executable/authme/debug/HasPermissionChecker.java:[106,21] incompatible types: inferred type does not conform to upper bound(s)
[ERROR] inferred: ? extends fr.xephi.authme.permission.PermissionNode
[ERROR] upper bound(s): java.lang.Object

**Comment by sgdc3** [comment]
@ljacqu any idea?

**Comment by ljacqu** [comment]
@sgdc3 Yep, this is just like 7b3bd3f4ea2534bbabe4304b80d7139b942902f7. Travis seems to have issues with generics where Circle CI, our Jenkins and we, locally, do not. :/

**Comment by ljacqu** [comment]
@Gnat008, this looks really nice! 

- Could we log the password change in PasswordRecoveryService#generateAndSendNewPassword and in SetPasswordCommand? It's interesting to log fundamental changes to an account. (So here with the IP address, for example.)

- There are two ways we offer password recovery: one when the recoveryCodeLength setting is `0`, in which case we just set a new password and send it to the user by mail. If the length is `> 0`, we send a code to the user's email, and once this is submitted to us we give him a time window to set a new password.
  - :warning: `PasswordRecoveryService#generateAndSendNewPassword` sends out a new password, but at the same time allows the player to set a new password—this is a security issue in the `recoveryCodeLength > 0` case!
  - If `recoveryCodeLength > 0`, I would expect that the player is forced to set a new password with `/email setpassword` and that no password is sent to him by mail. Unless someone thinks this would be useful.

**Pull request merged**
