### PR TITLE
Implement ARGON2 hash

### PR DESCRIPTION
**Pull request by sgdc3**
#1150

### CODE REVIEW

**Comment by sgdc3** [comment]
@ljacqu we are only missing the test class i think

**Comment by ljacqu** [comment]
Looks good so far but it doesn't work yet ;) A hash will never be checked against its password successfully; you need to override `comparePassword` so it goes over the Argon2 class.

You can generate the test class for Argon2 by using `AbstractEncryptionMethodTest#generateTest`

**Comment by sgdc3** [comment]
> You can generate the test class for Argon2 by using AbstractEncryptionMethodTest#generateTest

How? XD

**Comment by ljacqu** [comment]
```java
     /** Generates a test class for a given encryption method. Simply create a test class and run the following code,
     * replacing {@code XXX} with the actual class:
     * <p>
     * <code>@org.junit.Test public void generate() { AbstractEncryptionMethodTest.generateTest(new XXX()); }</code>
     * <p>
     * The output is the entire test class. */
```

So just create an Argon2Test class, and in it have the code posted above and you're good to go ;)

**Comment by sgdc3** [comment]
Test is failing, any idea?

**Comment by ljacqu** [comment]
Hopefully fixed it. Reason is the test was confused because Argon2 extends `UnsaltedMethod` but it's very much salted&mdash;we just don't have to worry about it ourselves.

**Pull request merged**
