### PR TITLE
Purge service architecture / permissions

### PR DESCRIPTION
**Pull request by ljacqu**
Request for comments.

Changes:
- Check all players for "bypass purge" permission before purging their data #784
  * Merge methods for default permission lookup into one
- Separate execution of purge actions from task creation (PurgeService vs. package-private PurgeExecutor)
- Fix execution of task #844
- More unit tests

### CODE REVIEW

**Comment by ljacqu** [comment]
Please review, and comment or merge

**Comment by sgdc3** [comment]
Looks good ;)

**Comment by sgdc3** [comment]
@Gnat008 @DNx5

**Comment by ljacqu** [comment]
@sgdc3, thanks :) And ref. @games647, original author of the PurgeTask

**Comment by sgdc3** [comment]
I was sure the author was @DNx5 :/

**Comment by sgdc3** [comment]
lol i like tags

**Comment by ljacqu** [comment]
There's one issue I still need to fix, and there's _at least_ one thing that's ugly about the design (but I don't know how to make it better). Let's see what the team finds :)

**Comment by ljacqu** [comment]
You snooze, you lose ;) 
I went ahead and merged it after another look at it. The state on master before merging didn't work at all, so this can't be worse... Reviews are still very welcome.

**Comment by Gnat008** [comment]
Whoops, I forgot to look at this again. Sorry. It all looks good, regardless.

**Comment by games647** [comment]
I love it. It looks a lot better.

**Comment by ljacqu** [comment]
Haha, cheers guys :smile_cat:
There's one thing that bothers me, it's that now we have `PermissionsManager#hasPermissionOffline(OfflinePlayer, PermissionNode)`, and `PermissionsManager#hasPermissionOffline(String, PermissionNode)` for lookups by name when we don't have an OfflinePlayer...

I thought about having our own dummy OfflinePlayer to create an object if we only have the name, but the OfflinePlayer interface has so many methods I'd find it even more ugly to have some dummy class like that... 
Initially the default permission evaluation just took a name and it loaded the player via Bukkit#getOfflinePlayer. I don't want this because a lookup to the server like that doesn't belong in a simple enum at all, but in the end I feel like I switched one ugly thing for another ugly one.

**Comment by Gnat008** [comment]
Yeah I find that dealing with OfflinePlayers almost always gets ugly quick. :/

**Pull request merged**
