### PR TITLE
Config option to disable GeoIP database

### PR DESCRIPTION
**Pull request by 3meraldK**

### CODE REVIEW

**Comment by ljacqu** [comment]
I don't think the constructor is the correct place to check for this, but rather in `isDataAvailable()`. It's not just called by the constructor but also in lookup methods, so it would be better to properly catch it in `isDataAvailable` and to avoid conditional logic in the constructor.

**Review by sgdc3 — APPROVED** [review]

**Comment by 3meraldK** [comment]
Requesting @ljacqu to review

**Comment by ljacqu** [comment]
Two unit tests fail, and I think we don't need the `enabled` field since all public data methods go through `getCountry()` -> I will fix this

**Comment by ljacqu** [comment]
The changes are now on master. Thanks!

**Pull request closed without merging**
