### PR TITLE
Package cleanup [Please Review]

### PR DESCRIPTION
**Pull request by sgdc3**
@ljacqu

### CODE REVIEW

**Comment by ljacqu** [comment]
I can do a review tomorrow ;)

**Comment by sgdc3** [comment]
@ljacqu Ok, thank you ;)

**Comment by ljacqu** [comment]
Nice, thanks for doing this!

I want to keep the Git history as much as possible so I've done a cherry pick of the changes in this branch with some alterations as given below. All of the changes are up for discussion, so if you (sgdc3) or anyone from the team have some disagreements with me please voice your opinion.

- authme.cache -> authme.data: great choice ✓
- StringUtils#makePath() -> FileUtils#makePath: that's fine; nice that you also moved the test :smile:
- LimboCache -> LimboStorage: I don't really agree with this, LimboCache is a contrast to PlayerDataStorage, which really _stores_ the PlayerData instances in file system. Maybe we can find another way to keep this constrast. Personally I would prefer maybe something like LimboPlayer / LimboCache / LimboStorage
  - You renamed PlayerData back to LimboPlayer, in my opinion good ✓ (PlayerData is a little too general and could suggest this is where we store login data or something) 
  - PlayerDataStorage wasn't renamed but the test class was renamed to LimboPlayerStorageTest; renamed main class as well ;)
  - For above reason I keep LimboCache; this gives us LimboPlayer / LimboCache / LimboPlayerStorage
- authme.datasource -> authme.datasource.backends: I don't like this; MySQL etc. are literally [datasources](https://en.wikipedia.org/wiki/Datasource) in the most traditional sense.
- authme.converter to authme.datasource.converter: Not my favorite (because our handling of the datasource is quite apart from the converters)
  - but it makes sense semantically, so I propose a compromise in the cherry pick by keeping datasource classes in datasource and moving converters to datasource.converter, is that agreeable? :wink: 
- Messages from message package to output -> fine ✓
- PluginHooks: "TODO split into single hooks classes": what's the benefit? If there is one please create an issue (easier trackable than a todo message in code). Not taken into cherry pick
- GeoLiteAPI -> GeoIpManager: OK, fine either way

**Comment by sgdc3** [comment]
Ok, i agree with your corrections ;)

Only one thing: LimboCache has no reason to be defined as a cache

**Comment by ljacqu** [comment]
Thank you, and you're right. Do you have a suggestion? I tried thinking/searching, best I've got right now is maybe LimboPlayerMemoryStorage which could contrast LimboPlayerFileStorage, but both are so long...

**Pull request closed without merging**
