### PR TITLE
Initial commit for help_zhhk.yml

### PR DESCRIPTION
**Pull request by lifehome**
Until the help_en.yml is filled with other strings, or I have more free time to extract the strings, the file will be referencing to the content of help_en.yml.

### CODE REVIEW

**Comment by sgdc3** [comment]
@ljacqu ok to merge? :)

**Comment by sgdc3** [comment]
or we should wait for the full translated file?

**Comment by ljacqu** [comment]
hi @sgdc3, for me it's fine either way, though if we expect more to come I'd rather keep it open.

@lifehome FYI, if you need a full help file, here it is:
https://hastebin.com/caxucidali.vbs

**Comment by sgdc3** [comment]
@lifehome any news? :) Should we merge this as it is for the moment?

**Comment by lifehome** [comment]
Ouch, missed the messages. Maybe merge it first? I am busying with other plugin's update, since Java 9 breaks a lot of plugins.

**Comment by sgdc3** [comment]
Ok, thank you :)

**Pull request merged**
