### PR TITLE
Packet based movement freeze

### PR DESCRIPTION
**Pull request by sgdc3**
Replaces the old limbo-based movement freeze with a simpler packet-based solution.

**TODO**:
- [ ] Testing

### CODE REVIEW

**Comment by ljacqu** [comment]
Excellent work! With the new way of logging on master this branch now has some compile issues remaining, after that I think we should merge :)

**Comment by sgdc3** [comment]
@games647 i need some help to make the code compatible with 1.8, if i remember correctly the flying speed was set with the "player abilities" packet at the time...

**Comment by sgdc3** [comment]
I actually used the wrong packet guys xD

**Comment by sgdc3** [comment]
It wasn't ready 😱

**Comment by sgdc3** [comment]
Shit it was still broker 🤣

**Pull request merged**
