### PR TITLE
#293 Translatable help section

### PR DESCRIPTION
**Pull request by ljacqu**
PR for #293, currently a very rough implementation.

Open ends:
- Help file needs to follow the language configuration
- Test values in help_en.yml obviously need to be changed
- If a section's text (e.g. "Alternatives") is empty, should we skip the entire section? Seems like this would be desired by some
- The help header text should be an entry in help_xx.yml and should be removed in config.yml
- I think it's desired by some to disable the help altogether?? Or just some commands? This could be visited in a second iteration
- Creating & fixing unit tests

Handling of default messages:
- I dont want to remove the description field on CommandDescription because I think it documents the code in CommandInitializer (it's easy to find out what command does what). Especially also for a description of the arguments.
- This poses the question what should be put inside help_en.yml. It's a little ugly to duplicate all of the messages in help_en.yml.

### CODE REVIEW

**Comment by ljacqu** [comment]
If someone has time to look at this—help_en.yml is how the file would kind of look like, if someone has comments to this, please let me know.

**Comment by sgdc3** [comment]
@ljacqu could you sync this with the main branch and fix test?

**Comment by ljacqu** [comment]
I will, I have some local changes I need to commit first

**Comment by ljacqu** [comment]
I'd like to explain how HelpProvider works. It has different sections that can be enabled / disabled with bit flags:

```java
    /** Set to show a command overview. */
    public static final int SHOW_COMMAND          = 0x001;
    /** Set to show the description of the command. */
    public static final int SHOW_DESCRIPTION      = 0x002;
    /** Set to show the detailed description of the command. */
    public static final int SHOW_LONG_DESCRIPTION = 0x004;
```
So each of these constants is something like "0001", "0010", "0100" in binary, which means you can call the `outputHelp()` method with the options you want:
```java
helpProvider.outputHelp(sender, foundCommand, SHOW_COMMAND | SHOW_LONG_DESCRIPTION);
// Last argument in binary: 0001 | 0100 = 0101
```

Then in the code we can check if the bit flag was enabled:
```java
// 0001 & 0101 = 0001 -> != 0, so enabled
if ((SHOW_COMMAND & options) != 0) {
  // show command if bit flag enabled
}
```

Now additionally it is possible to disable sections by having an empty translation. Instead of cluttering the code with checks for each translations everywhere, we create a new field with all enabled sections' bit flags and just filter incoming options against this. (See `filterDisabledSections()`.)

For example, if the translation for "SHOW_LONG_DESCRIPTION" is empty but the other ones have text, this will make the field enabledSections = SHOW_COMMAND | SHOW_DESCRIPTION (i.e. all bit flags besides SHOW_LONG_DESCRIPTION). So enabledSections is 0001 | 0010 = 0011 in this example.

Now when options = 0101 comes into HelpProvider, we check the options against this enabledSections number:
```java
// 0101 & 0011 = 0001
options = options & enabledSections;
// Options now doesn't have any bit flags of disabled sections anymore
```

**Pull request merged**
