### PR TITLE
#1026 Add more tags for forced commands (lazily replaced)

### PR DESCRIPTION
**Pull request by ljacqu**
- Extract lazy replacement of tags into its own class
- Implement wrapper to replace a String property within an object
  - Use wrapper in command manager and add new tags

Haven't done any performance measurements of this vs. naïve implementation. I suspect naïve would be faster.

### CODE REVIEW

**Comment by sgdc3** [comment]
Is it ready for merge?

**Comment by ljacqu** [comment]
In my opinion, it is.

**Comment by sgdc3** [comment]
Ok, looks good for me ;)

**Comment by ljacqu** [comment]
Thanks! :)

**Pull request merged**
