### PR TITLE
745 captcha login message

### PR DESCRIPTION
**Pull request by sgdc3**
#745

@ljacqu could you help me with unit test? :)

### CODE REVIEW

**Comment by sgdc3** [comment]
Thank you, i still need to test if cancelling a bukkitrunnable acts like cancelling the task.

**Comment by Xephi** [comment]
TODO : I tried to fix some conflict from Github editor directly, need to fix the merge from master before merge into master :')

**Comment by Xephi** [comment]
Merge fixed, need to fix the unpassed test

**Comment by sgdc3** [comment]
I'm not sure this would work as we save a BukkitRunnable, not a task :/

**Comment by ljacqu** [comment]
I can test this on Thu and squash the commits from Xephi into one

**Comment by ljacqu** [comment]
Verified behavior successfully, will merge into master with the commits from Xephi squashed :wink:

**Pull request closed without merging**
