### PR TITLE
Specify the Driver Class Name ("com.mysql.cj.jdbc.Driver")

### PR DESCRIPTION
**Pull request by MacacoLew**
TODO: Configurable Driver Class Name

### CODE REVIEW

**Comment by ljacqu** [comment]
Fine by me if we can make it configurable (we can give you pointers if you need), and would be interesting if you could share the background to this addition?

**Comment by MacacoLew** [comment]
> Fine by me if we can make it configurable (we can give you pointers if you need), and would be interesting if you could share the background to this addition?

I will update this PR to make the class name configurable soon, and i maked this PR because AuthMe in MYSQL Mode stop the server because doens't recognize the mysql server. (Latest MySQL library in my fork, and this PR fixs it, tested)

**Comment by MacacoLew** [comment]
> Fine by me if we can make it configurable (we can give you pointers if you need), and would be interesting if you could share the background to this addition?

U like the changes? say me if im wrong with some typos if u can :), im spanish and my english is not good too.

**Comment by sgdc3** [comment]
Looks good, thank you :)

**Pull request merged**
