### PR TITLE
New Chinese Translation with all lines translated

### PR DESCRIPTION
**Pull request by tsangsiuki12**
I translated all lines with new lines translated in a different tone and interpretation for macau people

### CODE REVIEW

**Comment by sgdc3** [comment]
Hello

>usage_captcha: '&3To login you have to solve a captcha code, please use the command "/captcha <theCaptcha>"'
wrong_captcha: '&cWrong captcha, please type "/captcha THE_CAPTCHA" into the chat!'

you have to keep <theCaptcha> and THE_CAPTCHA, they are replaced with variables ;)

**Comment by tsangsiuki12** [comment]
Hello, I have fixed the part you have mentioned,hope this would be useful for your plugin:]

**Comment by sgdc3** [comment]
@ljacqu Seems valid now, right?

**Comment by ljacqu** [comment]
Hi @tsangsiuki12, thanks for doing this. One last tag is missing: `<theCaptcha>` in the entry for `usage_captcha`.

You say that this is the Macau variant, which I'm guessing is Cantonese? Is this a big difference from the Hong Kong variant (which I presume is also Cantonese)?

**Comment by tsangsiuki12** [comment]
the hong kong variant is in spoken language, which is difficult to add translation to the new lines as to match its tone. Also, in my opinion translate it into written language would be more suitable and better, therefore i made a complete overhaul with all the new lines translated and differentiate it from its Spoken Cantonese translation.

**Comment by ljacqu** [comment]
@tsangsiuki12 Thanks a lot for doing this translation and for the explanations you've provided. If I understand correctly, your file would also be suitable for players from Hong Kong?

**Comment by tsangsiuki12** [comment]
yep.

**Pull request merged**
