### PR TITLE
Improves spawn choice if undefined

### PR DESCRIPTION
**Pull request by Hex3l**
#1700

### CODE REVIEW

**Comment by ljacqu** [comment]
1) The for-loop `for (String priority : spawnPriority)` on L176 will by default always return a location so the loop you've added, I expect, will not be executed in many cases (for sure whenever the spawnPriority includes "default"). Seeing as your location check is quite lenient I would suggest to perform this check also before L202 when the spawnLocation is returned.

2) I think it would make sense to cache the world default spawn location. We shouldn't optimize for that case but I still think it might be worthwhile to have a field with the world that gets lazily initialized the first time we need it (the result of L211)

3) Minor: you could simplify the method to `return location.getX() != 0 || location.getY() != 0 || location.getZ() != 0` if you like, or just keep it as it is, of course. There's nothing wrong with it. :)

**Comment by Hex3l** [comment]
The idea was to provide a working spawn system while AuthMe is not configured properly.

1. By default the configuration uses `spawnPriority: authme` , so the for-loop `for (String priority : spawnPriority)` will always trigger only the `authme` case. In this case we have two situations: 
    1. An authme spawn exists in the spawn.yml
        - In this case the user has manually set a spawn point so that spawn point will be used.
    2. There are no spawn points in the spawn.yml
        - In this case the for-loop ends and the `spawnLoc` will be null

   Since the spawn location is null the new validation for-loop will be triggered. 
An other way to handle this, as you suggested, is to place the validation for-loop at L182 and change the default configuration to something like `spawnPriority: authme,default`. Since this check refuses only the location (0,0,0) this new option could actually be a better implementation, but should also be noted a potential performance loss in extreme cases.

2. The idea was to cover the "not properly configured" case, that's why the warn should allert the end user to properly set a spawn location avoiding the hypothetical performance loss.

3. Thought it was more readable ^.^

I can't decide between the two implementation at point 1 because I think they have similar down sides so, I'm gonna rely on your choice 😄

**Comment by ljacqu** [comment]
1. As far as I see in the code the default right now is "authme,essentials,cmi,multiverse,default". 

2. Totally agree, nothing to do here :)

**Comment by Hex3l** [comment]
Well, seems like I had an old configuration 🤦‍♂
I'm going to move the verification + for-loop in the "default" case, sorry about that 😅

**Comment by ljacqu** [comment]
Removing the release milestone since the issue this is for is already labeled as such -> keeps our bookkeeping free of duplicates

**Pull request merged**
