### PR TITLE
Update the GeoIp database download method [BREAKING]

### PR DESCRIPTION
**Pull request by sgdc3**
Now GeoIp database updates require a ClientID and a LicenseKey, which can be obtained for free at https://www.maxmind.com/en/accounts/current/license-key

### CODE REVIEW

**Comment by sgdc3** [comment]
#1979

**Comment by Xephi** [comment]
Maybe we can let users choose between downloading the whole database or using the api directly ? 
https://github.com/maxmind/GeoIP2-java

**Comment by ljacqu** [comment]
Great job! I have two questions about error scenarios:
1. if one of the config values is empty, could we log something meaningful? (Pointing them to the config.yml, maybe to the properties‘ path)
2. if the download somehow fails, the plugin should still work and start up normally, right?

**Comment by sgdc3** [comment]
@Xephi the api isn't as fast as the local db, i personally had issues with antibot plugins using the rest api, due to rate limits and the performance impact

**Comment by sgdc3** [comment]
@ljacqu 
1) Ok, there is already a message but it doesn't point to the config path
2) Yes, the geoip check will just be ignored, and a warning message will be printed on startup

**Pull request merged**
