### PR TITLE
Implement onSessionLogin trigger for commands.yml

### PR DESCRIPTION
**Pull request by sgdc3**
#1090 
Needs test methods, @ljacqu any advice?

### CODE REVIEW

**Comment by ljacqu** [comment]
Cool! :smile:
On mobile right now – whatever the other tests do you can probably also do for this new section

**Comment by sgdc3** [comment]
@ljacqu Could you explain me why onLogin has 2 tests? (the complete/incomplete commands.yml check)

**Comment by ljacqu** [comment]
@sgd3 Unit tests should kind of cover the cases we expect to happen — one case is there being commands in the commands.yml, but another case is that there is an empty commands.yml. When I wrote these tests I was just trying to cover as many cases as possible with reasonable effort.

**Comment by ljacqu** [comment]
hi @sgdc3, this is the last issue in the 5.3 milestone

**Comment by sgdc3** [comment]
I'm atm busy with exams, i'll try to do that this weekend

**Pull request merged**
