### PR TITLE
427 register with pass and email

### PR DESCRIPTION
**Pull request by ljacqu**
Implementation to allow `/register password email` (#427). Handled by introducing a new RegisterType enum that defines what arguments the `/register` command expects.

I plan to clean this up a little by adding more specific methods to the AsyncRegister class. Right now, there's only one method we call, regardless of what registration type we have, and this has become quite a mess as we've added to it.

### CODE REVIEW

**Comment by ljacqu** [comment]
This is ready to be merged now. 

A few comments about the refactor this contains: it separates the async register process into various classes, so called "registration executors." AsyncRegister receives one such executor and does all of the common stuff (like checking that no such name is registered) but delegates other stuff to the executor for specific stuff (like generating a code for 2FA registration). 

There is room for improvement, namely the inner classes of the *ExecutorProvider classes are quite ugly. For now we have to do it this way because we want to have access to `@Inject` fields. The injector currently doesn't support inheritance, so everything needs to be structured like this.

Secondly, the inner classes in the password registration executors have some weird inheritance. I don't like that 2FA extends from password registration and then overrides the checks it does. This is because of the above restriction; once this is solved I'd like to have an abstract common class from which password registration and 2FA registration will extend, rather than have 2FA extend from the password registration executor directly.

If this PR gets accepted I'll create a follow-up issue for these points and I'll make sure that we'll have a new injector release soon with the missing features.

**Comment by sgdc3** [comment]
Looks good for me ;) What do you think @Xephi @Gnat008 @games647 @DNx5 ?

**Comment by ljacqu** [comment]
Once inheritance works with the injector we could even look into adding more of the specific logic into classes (like checking if the arguments are correct). Essentially we could only check _once_ which registration type to have, namely to decide which implementation to instantiate.
The real issue with that approach is how to fit it into our typical pattern of delegating to the Management class to start an async task. I'm not suggesting we go through it if it doesn't work organically, but it's still nice to have a somewhat consistent pattern in the codebase :)

**Comment by ljacqu** [comment]
Thanks for the feedback! I wanted to test this in the game before merging today, but I'll have to do so tomorrow... :)

**Comment by koca2000** [comment]
Please add message for new command. When you enter server it still say you "Please register with /register password password"

**Comment by koca2000** [comment]
Also when you register using command /register password email it say you: "Please add your email...."

**Pull request merged**
