### PR TITLE
First attempt to implement MsSQL datasource

### PR DESCRIPTION
**Pull request by sgdc3**

### CODE REVIEW

**Comment by sgdc3** [comment]
#1302

**Comment by sgdc3** [comment]
lol codeclimate isn't happy

**Comment by ljacqu** [comment]
Sorry for the late reply & thanks for waiting. I checked out the branch and went through the changes. A+ :smile:

**Comment by sgdc3** [comment]
good, but it doesn't work xD

**Comment by sgdc3** [comment]
Too difficult all the queries are different, i think PostgreSQL support would be better.

**Comment by sgdc3** [comment]
I'll keep the branch as it contains the SQLDataSource abstraction class that might be useful in the future

**Pull request closed without merging**
