### PR TITLE
Translate messages_pt.yml

### PR DESCRIPTION
**Pull request by rafael59r2**

### CODE REVIEW

**Comment by ljacqu** [comment]
Thanks for this! At the end of `incomplete_email_settings` the message is in English. Shall we copy this pull request open to fix this?

**Comment by rafael59r2** [comment]
done

**Comment by ljacqu** [comment]
> Por favor **cotate** um administrador

Shouldn't it be "contate" ?

**Comment by rafael59r2** [comment]
Yes, sorry my mistake

**Comment by ljacqu** [comment]
Thanks! Now we can merge~ :smile:

**Pull request merged**
