### PR TITLE
Update messages_ko.yml

### PR DESCRIPTION
**Pull request by Adeuran**
Additional Translate by Adeuran(아몬드노란맛 http://adeuran.tistory.com)

### CODE REVIEW

**Comment by ljacqu** [comment]
The message key 'captcha_for_registration' has a tag `<theCaptcha>` which AuthMe replaces to the actual captcha code. Please add it back to the message and we'll be able to merge.

**Comment by sgdc3** [comment]
@ljacqu we should change it to %captcha%, in general we should use %% to mark placeholders.

**Comment by ljacqu** [comment]
@sgdc3 On the 1467 branch all placeholders have been changed to `%name`

**Comment by sgdc3** [comment]
Uh missed that, very nice! :D

**Comment by Adeuran** [comment]
I think CAPTCHA 코드(captcha code) is easier than 자동가입방지문자 to understand and more natural.
Thank you.

**Comment by ljacqu** [comment]
Thanks!

**Pull request merged**
