### PR TITLE
Get Czech localizations to 100%

### PR DESCRIPTION
**Pull request by dusekdan**
Hello!

It's Hacktoberfest time again and I would like to contribute to AuthMeReloaded with localization to my native language.

In this pull request, I have:

- translated all the TODO resource strings 
- added help_cz localization file and translated all the resource strings contained
- unified the voice, or tone, which is used in both localization files; before this update, there was a mix up of the second case singular and second place plural when addressing a user of the plugin. I unified it to use 2nd case singular.

As time is of the essence in regards to Hacktoberfest, it would be greatly appreciated if you could merge my PR as soon as possible.

Thanks and keep up the good work!

### CODE REVIEW

**Review by MrIvanPlays — CHANGES_REQUESTED** [review]
would like someone speaking ur language to confirm there are no offensive words.
otherwise thank you for your contribution

**Comment by TheDevTec** [comment]
There is one grammatical mistake. In messages_cz.yml on line 133. `email_needed: '&3Pro ověřené tvé identity potřebujeme, abys ke svému účtu přidal svůj email.'` Correctly is: "..Pro ověřen**í** tvé identity..".

Everything else should be ok!

**Comment by dusekdan** [comment]
Thank you, for the review, @TheDevTec, I fixed it in the commit above. Do you think it's mergeable now @MrIvanPlays?

**Review by MrIvanPlays — APPROVED** [review]

**Comment by MrIvanPlays** [comment]
If there are no additional comments, I'm ready to merge it

**Pull request merged**
