### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by garagepoort**
Overload reload method to pass in a boolean to turn on/off the migration check.
Old method is still there.

### CODE REVIEW

**Review by ljacqu — CHANGES_REQUESTED** [review]
The failing test uses an old SQLite database, which has to be migrated (now for two reasons). I'm fairly sure the test fails because the migration code has issues. Fixing SqLiteMigraterIntegrationTest to not migrate anymore kind of beats the purpose

**Comment by ljacqu** [comment]
Fixed in https://github.com/AuthMe/AuthMeReloaded/commit/e92721e59741b6caf81fbe9c7612118a68f84251, thanks for raising awareness to the issue

**Comment by garagepoort** [comment]
I didn't remove the migration. I removed triggering the migration infinite times...

**Comment by ljacqu** [comment]
> I removed triggering the migration infinite times...

That's exactly my point: the test was failing because AuthMe (in the real code) would also trigger a migration infinite times. The issue was with the migration _itself_. 

>  Is it because the check now doesn't always return true after migration ?

Yes, the commit message explains why that was the case before.

**Pull request closed without merging**
