### PR TITLE
#605 Add custom log levels, create debug logging method

### PR DESCRIPTION
**Pull request by ljacqu**
Please review, and comment or merge.

Changes:
- Create LogLevel enum with `INFO`, `FINE` and `DEBUG`
   - Instead of checking `if (settings.getProperty(SecuritySettings.STOP_CONSOLE_SPAM)) ...` everywhere just call `ConsoleLogger.fine()` and let it figure it out
- Write the log levels in the log file too
- Create migration from old boolean "stop spam" property to new log level property

Issues:
- I wanted to initially use the standard logger levels, `INFO`, `FINE`, `FINER`, `FINEST`... Unfortunately the Java levels are not an enum so we need an enum class anyway (to get the setting and validate it the most easiest way)... Then I thought for the end user, for us, and for new developers it's a little bit odd if we say "FINE" is still quite relevant (e.g. "used the wrong password") and "FINER" would be debug messages. So I thought maybe we can mix levels and just call them INFO, FINE, and DEBUG. I'm open for other suggestions.
- Logging the levels in the log file, I want them to align properly, so there's an [INFO] prefix and [FINE]... Debug is 5 chars, so I used [EBUG]... Maybe makes more sense to write it out?

### CODE REVIEW

**Comment by Gnat008** [comment]
This looks pretty good to me. However, I think that [DEBUG] should be fully written out in the logs. It makes it a bit more intuitive for users to see what it is. It also looks less... Weird.  :P

**Comment by games647** [comment]
Isn't fine the same as debug? Log4j translates FINE, FINER, FINEST to Debug.

Moreover although removing all the no-console-spam checks is great, I think we should change the method signature of the logging methods to something like this

name(String format, Object[] args) - similar to the one of java util logging or sl4j logging. Then we could do lazy message formatting for debug messages? **Maybe this is  unnecessary for this project.** What do you thing?

**Comment by ljacqu** [comment]
@Gnat008 Thanks for the feedback, I'll write it out. You're right, I guess it's more important to have a clear word than alignment.

@games647 Thanks for your points - yes Log4j uses different log levels than the Java util logging. In AuthMe we have three different ones for non-error messages: standard INFO message, those "stop console spam" messages, and debug. INFO, FINE and DEBUG is the best I can come up with for those intentions, but maybe you have a better suggestion? I agree that it's ugly to reappropriate log names from _two_ different log systems. 
I don't want to use Java util INFO, FINE and TRACE because TRACE is way too low than what we want to do with it (namely add a few debug statements). Add the same time I don't want to use INFO, FINE and FINER (or FINEST) because FINE is way different from the debug level, in my opinion.

Finally, method signature, I'd be all for `String format, Object... args` but this is a log4j thing. Bukkit returns a java util Logger object, which only has `info(String)` (etc.)

**Comment by games647** [comment]
>Finally, method signature, I'd be all for String format, Object... args but this is a log4j thing. Bukkit returns a java util Logger object, which only has info(String) (etc.)

What about log(Level ....)?

What about INFO, WARNING, DEBUG (including all fine-levels)?

**Comment by ljacqu** [comment]
> What about log(Level ....)?

Totally missed that one ;) One problem with this is when want to log to the authme.log file as well? Then we have to handle the logic of applying the replacements outside of the logger.

---

> What about INFO, WARNING, DEBUG (including all fine-levels)?

One implementation note, the "FINE" and "DEBUG" I want to introduce are being logged on INFO level because Bukkit logger configuration ignores everything below "INFO". So if you do `getLogger().fine("Test")` in your plugin it won't show in the console.
_Our_ "FINE" logs to INFO level if "fine messages" are enabled (as defined in config.yml), and "DEBUG" would be the same - also logs to INFO level but with a "Debug:" prefix.

**Comment by games647** [comment]
>because Bukkit logger configuration ignores everything below "INFO

Got it. Good point

>Totally missed that one ;) One problem with this is when want to log to the authme.log file as well? Then we have to handle the logic of applying the replacements outside of the logger.

Maybe we could use the SimpleFormatter from Java.

**Comment by ljacqu** [comment]
>>     because Bukkit logger configuration ignores everything below "INFO

> Got it. Good point

Thanks. Unfortunately this blocks us from using the logger in a sensible way, that's why this PR would basically roll out our own level system (for things below INFO) and then always log to INFO. :( 

> Maybe we could use the SimpleFormatter from Java.

That would be pretty cool! I have to say I really like log4j's `{}` placeholders. I even think we might be able to set up some validation in IntelliJ, as it does e.g. in String.format() when the arguments don't match the formatted string.

**Comment by ljacqu** [comment]
@games647 Looks like there's no way to make IntelliJ validate custom methods like it does for `String.format()` & friends. I'm not really inclined to add similar methods to ConsoleLogger if we don't have the possibility to see a warning in the IDE on misuse. What do you think?

**Comment by games647** [comment]
I know IDEs helps there a lot, but there are other IDEs out there. That doesn't have this check for normal methods.

**Comment by ljacqu** [comment]
Would eclipse support such a thing?

**Comment by ljacqu** [comment]
Tell you what, I don't want to implement it if I can't configure some IDE warnings (because it will be hard to find out when a `String.format()`-like method has a problem), however if _you_ want to implement it then please go ahead! It would be a cool addition.

Closing PR as these changes here are applied to master as a squashed commit. If something should still be improved (I'm still very open for other log level names), please let me know.

**Pull request closed without merging**
