### PR TITLE
Add delay option into Commands config

### PR DESCRIPTION
**Pull request by DNx5**
Related Issues
#1449 #1042

### CODE REVIEW

**Comment by ljacqu** [comment]
Hi @DNx5 , the code looks great to me :smile: How can I help with the unit tests?

**Comment by DNx5** [comment]
I think there should be a Test to verify is command executed after specified delay.
Still not sure if that's necessary.

**Comment by ljacqu** [comment]
OK, I‘m on it :)

**Comment by sgdc3** [comment]
@DNx5 @ljacqu any news? ;)

**Comment by ljacqu** [comment]
ah ffs since the upgrade to ConfigMe 1.0.1 if I run the tests (with the changes in here or without) of CommandManagerTest in debugger they fail, but in normal execution they work just fine...

**Comment by ljacqu** [comment]
The diff in this PR now appears really strange, I'll merge manually with Git to make sure there isn't more in this PR than the implementation for the command delays. But I'm fairly sure GitHub just did something strange when those new changes came in.

**Comment by ljacqu** [comment]
Merged all changes besides my last commit manually—therefore closing this PR

**Pull request closed without merging**
