### PR TITLE
#1435 Send password recovery emails in async

### PR DESCRIPTION
**Pull request by ljacqu**
Haven't been able to test this in-game. I'll do it tomorrow. If someone wants to have a look at the code until then, please do :)

### CODE REVIEW

**Comment by kacperduras** [comment]
Curiosly I tested this fix - works great ;)

**Comment by sgdc3** [comment]
Tested, seems to work as intended ;)

**Comment by sgdc3** [comment]
#1435

**Comment by ljacqu** [comment]
Thanks for the feedback :)

**Pull request merged**
