### PR TITLE
LuckPerm: keep contexts active after reload of groups 

### PR DESCRIPTION
**Pull request by garagepoort**
We noticed that AuthMe removes the contexts set by luckperm if we enable the option: enablePermissionCheck
This means that after authentication a user might get a group that should not be active.

For example a user is given group: "Titan" with context "Server=Classic"
The user logs in on server "Other".
Because AuthMe, removes and adds the groups the context is lost.
I created this PR to keep the context after reloading the groups.

### CODE REVIEW

**Review by sgdc3 — APPROVED** [review]

**Comment by sgdc3** [comment]
Looks good to me 👍

**Comment by garagepoort** [comment]
@sgdc3 @ljacqu 
not to sound impatient but will this get merged?

**Comment by sgdc3** [comment]
@ljacqu @games647 @Hex3l can somebody review this too please?

**Comment by garagepoort** [comment]
hey @sgdc3 
My hopes are not too high. But will this get merged?

**Comment by sgdc3** [comment]
@ljacqu @games647 @Hex3l any opinion on this?

**Review by sgdc3 — APPROVED** [review]

**Comment by sgdc3** [comment]
@garagepoort sorry for the delay, I wanted to wait for a review by the other contributors but they seems to be busy atm :)

**Pull request merged**
