### PR TITLE
[Messages_IT] Add message entry for each registration type

### PR DESCRIPTION
**Pull request by Maxetto**
At:
`reg_psw_email_msg: '&3Per favore, esegui la registrazione con il comando: "/register <password> <email>"'`

Are you sure it's `/register <password> <email>` and not `/register <email> <password>`?

### CODE REVIEW

**Comment by koca2000** [comment]
It's `/register <password> <email>`

**Comment by ljacqu** [comment]
Thanks @Maxetto , it's great to have someone that takes care of his language :smile:

**Comment by sgdc3** [comment]
:( @ljacqu xD

**Comment by ljacqu** [comment]
@sgdc3 This is not a jab at you, in case the sad smiley means that. I don't maintain "my" languages either ;)

**Comment by sgdc3** [comment]
I know i was joking xD

**Pull request merged**
