### PR TITLE
792 registration date and ip

### PR DESCRIPTION
**Pull request by ljacqu**
Third attempt at implementing #792, but this time it's looking good ;)

I still have a last commit coming for this PR. I'm happy for remarks and questions in the meantime ;3

This PR contains the following changes:
- introduction of registrationDate and registrationIp columns
- adjust purging logic to use both registrationDate and lastLoginDate
- is it OK that I drop the "all" argument in `/authme purge`? I don't think it's needed anymore
- new command `/authme debug mysqldef <add/remove> <column>` allows a user to toggle the `NOT NULL` constraint... so far for the email column and for the last login date.
  - Includes a change in semantics: when reading the default value from the DB and creating a PlayerAuth (e.g. `your@email.com` in `PlayerAuth`), the resulting PlayerAuth will have `email = null`

### CODE REVIEW

**Comment by sgdc3** [comment]
@ljacqu Nice job! Fix the conflicts and we are ready to merge ;)

**Comment by sgdc3** [comment]
Merged, doing some minor cleanup now

**Comment by sgdc3** [comment]
One test is currently failing, any idea? :/

**Comment by ljacqu** [comment]
No, please don't merge yet! I have local changes to fix the column adding

**Comment by sgdc3** [comment]
Whoops, sorry, didn't know that, i just fixed some conflicts.

**Comment by ljacqu** [comment]
@sgdc3 @HexelDev Unfortunately SQLite doesn't allow to change column definitions or drop columns later on. This sadly forces me to implement a migration that will rename the current table to a temp one, recreate a new table and copy over the data from temp to the new one...

It is necessary because on registering a PlayerAuth we no longer set the `lastIp` field. Yet, in older setups of SQLite the `lastIp` field was set to `NOT NULL` with no default.

Renaming a table and copying its data is a bit risky so we want to ensure that the player will make a backup first. The way I handle this is that I log a WARNING on SQLite startup if a migration is required, and the actual migration is under `/authme debug sqlitemigration`. Running that command will show a warning to make a backup along with a code to actually run the migration (e.g. `/authme debug sqlitemigration SFYT`). 
This way it is not run automatically and the user is explicitly asked to perform a backup.

Is this OK for you? Do you have suggestions to improve the process?

**Pull request closed without merging**
