### PR TITLE
#1015 Implement lazy replace of tags for welcome message

### PR DESCRIPTION
**Pull request by ljacqu**
I'd like some feedback on this. I tried to solve the inefficient approach in which the welcome.txt is handled: it has tags that can be replaced, for each line we get all of the tags values and replace them. This includes things like the player's country, his IP address, and the number of online players.

Solution for this was to get the values only once and to store them in a list, and to keep a list of used tags when we load the welcome message so we don't spend time trying to replace tags that aren't used (i.e. don't get the player's country if that tag isn't used...).

The logic can be potentially reused elsewhere, e.g. for the forced commands.

Advantages of this approach
\+ Don't perform work that isn't necessary each time a player logs in
\+ May be interesting in the future if more "inefficient" tags are introduced / to also use elsewhere

Disadvantages of this approach
\- Complicates the codebase (handling the welcome message now requires its own class)
\- The performance improvement is not bad percentually (~40%), but we're talking on a scale of _nanoseconds_. Fetching the country isn't really slow because GeoLite caches its results.
   \-> But if this is the only place the player's country is fetched, it's still dumb to do it

### CODE REVIEW

**Comment by sgdc3** [comment]
:+1:

**Comment by ljacqu** [comment]
Hi @games647, any thoughts? :)

**Comment by games647** [comment]
>- Complicates the codebase (handling the welcome message now requires its own class)

I don't think it's so complicated, but it could confuse other developers if they are new to Java 8.

>+ Don't perform work that isn't necessary each time a player logs in

Isn't currently the {ONLINE}-variable constant although it shouldn't?

**Comment by ljacqu** [comment]
Thanks for the feedback, @games647 ! :)

> it could confuse other developers if they are new to Java 8

Fair point, that's also a reason as to why I didn't use any streams to apply the replacement—the main reason was performance: LinkedList has fast insertion and iteration, and streams have a certain overhead. If someone has a question about the impl please feel free to ask.

> Isn't currently the {ONLINE}-variable constant although it shouldn't?

I don't think so, right? We keep the tags we need to replace in `WelcomeMessageConfiguration#usedTags`, and each time we need the welcome message for a player we call the tags lambda:

```java
new Tag("{ONLINE}",  () -> Integer.toString(bukkitService.getOnlinePlayers().size()))
// ^ executed each time getWelcomeMessage(Player) is called
```

**Pull request merged**
