### PR TITLE
ru: update

### PR DESCRIPTION
**Pull request by Jerozgen**

### CODE REVIEW

**Comment by sgdc3** [comment]
@ljacqu Could you review this? I think @Jerozgen removed some placeholders like the captcha one.

**Comment by ljacqu** [comment]
@sgdc3 you're right, if the tests had run one would have failed

**Comment by sgdc3** [comment]
@ljacqu I managed to fix the ci builds this morning, i also fixed some old github hooks that were broken since we moved the main repository

**Comment by sgdc3** [comment]
OK, i started a new build on travis, this is the issue that is failing:
https://travis-ci.org/AuthMe/AuthMeReloaded/builds/247800940#L2250

```
- Message key 'usage_captcha' should have tags: <theCaptcha>
- Message key 'wrong_captcha' should have tags: THE_CAPTCHA
```

**Comment by sgdc3** [comment]
@Jerozgen Could you please fix that? ;)

**Comment by ljacqu** [comment]
@sgdc3 Thank you for your work :)

**Pull request merged**
