### PR TITLE
Playerdata fix

### PR DESCRIPTION
**Pull request by ljacqu**
Hi @DNx5, could we ask you for a status update on this?

### CODE REVIEW

**Comment by DNx5** [comment]
i'm no clue with this thing, people really hate it.

**Comment by sgdc3** [comment]
>i'm no clue with this thing, people really hate it.

???

**Comment by DNx5** [comment]
I mean, i don't have better implementation to store player's restriction state other than using json files.
Maybe we could use protocollib to apply player restriction effect. but for group and last location, I don't think so.

**Comment by DNx5** [comment]
also, this branch is contains fix for player's data being persistent. but it make player's last location teleport no longer working.

**Pull request closed without merging**
